name: WildTTS / Data Preparation for Training

on:

  workflow_dispatch:


    

jobs:
  data-prep:
    runs-on: [self-hosted, arc]
    steps:
        - name: allocate_batch_job
          run: 
            cd ~/ensf619/WildTTS/training/campplus_finetuning 
            sbatch run_prepare_data.slurm

