name: WildTTS / Create target embeddings

on:
  workflow_dispatch:


    

jobs:
  target_embeddings:
    runs-on: [self-hosted, arc]
    steps:
        - name: allocate_batch_job
          run: | 
            cd ~/ensf619/WildTTS/training/campplus_finetuning
            sbatch run_generate_embeddings.slurm

