name: WildTTS / Create target embeddings

on:

  workflow_dispatch:
  push:


    

jobs:
  data-prep:
    runs-on: [self-hosted, arc]
    steps:
        - name: allocate_batch_job
          run: | 
            echo "registered"
            # cd ~/ensf619/WildTTS/training/campplus_finetuning
            # sbatch run_generate_embeddings.slurm

